version: 1
lang:
  buy-success: '<green><sm>Success!</sm></green> <white>You have purchased the</white> <yellow><hat></yellow> <white>for</white> <green>$<price></green>'
  insufficient-balance: '<red><sm>Error!</sm></red> <white>You do not have</white> <green>$<price></green>'
  activate: '<green><sm>Success!</sm></green> <white>You have put on the</white> <yellow><hat></yellow>'
  clear-hat: '<green><sm>Success!</sm></green> <white>You have remove your hat.'
  no-hat: '<red><sm>Error!</sm></red> <white>You do not have a hat on!</white>'

sounds:
  menu-open: 'ITEM_BOOK_PAGE_TURN'
  activate: 'ITEM_TRIDENT_RETURN'
  error: 'BLOCK_BONE_BLOCK_BREAK'

gui:
  owned:
    item: 'CHEST'
    display: '<red>Owned Hats</red>'
    title: 'Your hats:'
  shop:
    item: 'EMERALD_BLOCK'
    display: '<green>Hat Shop</green>'
    title: 'Hats for sale:'
  clear:
    item: 'BARRIER'
    display: '<red>Clear Hat</red>'

hats: {}
