name: hats
version: "1.0"
main: net.df1015.hats.HatPlugin
api-version: '1.21.1'
author: ringpolice

dependencies:
  server:
    popcorn:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: true
      join-classpath: true

permissions:
  vindex.hat:
    description: "Permission to open hat shop"
    default: not op
